### PR TITLE
Remove apiserver flock.

### PR DESCRIPTION
**Pull request by diegs**
The pivot and checkpointer both appear to work fine without it.

If this works, possibly a partial fix for #495

### CODE REVIEW

**Comment by diegs** [comment]
@aaronlevy  PTAL, I added a liveness probe to the apiserver as well.

**Comment by diegs** [comment]
cc @ericchiang

In order to make this work we need to enable anonymous auth on the apiserver, because the kubelet does not use authentication to probe (https://github.com/kubernetes/kubernetes/issues/9866)

The default permissions for unauthenticated users seem innocuous, but they are also not small:

https://github.com/kubernetes/kubernetes/blob/v1.7.0/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/testdata/cluster-roles.yaml#L373

**Comment by ericchiang** [comment]
Re: anonymous auth. I think a release notes and plans to turn on audit logging would suffice. We could also remove the default system:user-basic binding.

**Comment by rphillips** [comment]
@diegs can you rebase this PR to master to kick the build bot once more? I tried this change locally on master and everything booted correctly.

**Comment by diegs** [comment]
@rphillips done.

**Comment by redbaron** [comment]
what is the status of it? do we need flock at the end?

**Comment by diegs** [comment]
Let me give this another try now that the checkpointer has a grace period when swapping pods.

**Comment by diegs** [comment]
Going to run this locally a few times to make sure the behavior sane, and also rerun e2e.

**Comment by diegs** [comment]
coreosbot run e2e

**Comment by diegs** [comment]
coreosbot run e2e

**Pull request merged**
