### PR TITLE
checkpointer: ignore Affinity within podspec

### PR DESCRIPTION
**Pull request by rphillips**
Kubernetes 1.12.x introduced new logic for Affinity [1]. In addition to
new logic, the Pod contains a default affinity. The new default affinity
gets serialized into the checkpoint file, and the 1.12.x kubelet does
not restore the pod due to the affinity.

This PR removes the affinity from the spec and documents that affinity's
are not supported.

```
"affinity": {
      "nodeAffinity": {
        "requiredDuringSchedulingIgnoredDuringExecution": {
          "nodeSelectorTerms": [
            {
              "matchExpressions": null
            }
          ]
        }
      }
    },

```

[1] https://github.com/kubernetes/kubernetes/pull/68173
[2] https://github.com/kubernetes/kubernetes/blob/e39b510726113581c6f6a9c2db1753d794aa9cce/pkg/controller/daemon/util/daemonset_util.go#L183-L196

### CODE REVIEW

**Comment by rphillips** [comment]
@aaronlevy needs another lgtm

/cc @dghubble

**Comment by aaronlevy** [comment]
coreosbot run e2e checkpointer

**Comment by aaronlevy** [comment]
Because this is changing checkpointer code, the normal e2e tests are not explicitly testing the new functionality (the cluster is launched with existing checkpointer pod) https://github.com/kubernetes-incubator/bootkube/blob/master/pkg/asset/images.go#L12.

The checkpointer tests will build a new checkpointer image, then use that in the e2e tests.

**Comment by rphillips** [comment]
coreosbot run e2e checkpointer

**Comment by rphillips** [comment]
coreosbot run e2e checkpointer

**Comment by rphillips** [comment]
coreosbot run e2e checkpointer

**Comment by rphillips** [comment]
coreosbot run e2e checkpointer

**Comment by rphillips** [comment]
coreosbot run e2e checkpointer

**Comment by rphillips** [comment]
coreosbot run e2e checkpointer

**Comment by rphillips** [comment]
@dghubble mind lgtm again?

**Pull request merged**
