### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by xichengliudui**
Update README.md

### CODE REVIEW

**Comment by dghubble** [comment]
I'm confused. The existing links look correct to me. The code copied into [pkg/checkpointer/cri/v1alpha2](https://github.com/kubernetes-incubator/bootkube/tree/v0.14.0/pkg/checkpoint/cri/v1alpha2) does match what was in [kubernetes](https://github.com/kubernetes/kubernetes/tree/v1.10.0-rc.1/pkg/kubelet/apis/cri/runtime/v1alpha2) v1.10.0-rc.1.

**Comment by xichengliudui** [comment]
@dghubble  Thanks for the tip, but shouldn't we show the latest version of cri

**Comment by dghubble** [comment]
The message is supposed to indicate where the code was taken from, for internal implementers to not lose track of. If there's a need to bump to the code from v1.11 or v1.12, it could be bumped and *then* this change would be accurate.

**Comment by xichengliudui** [comment]
@dghubble  Do I need to turn it close?

**Comment by dghubble** [comment]
Yeah, I think this can be closed

**Pull request closed without merging**
