### PR TITLE
recover: relax verification of etcd CAPath

### LINKED ISSUE #903: bootkube recovery requires an etcd client cert when used with an ca cert.
bootkube recovery requires that you provide a etcd-client cert and key when you specify a etcd-ca-cert.

This should not be a requirement. Etcd can be secured by a CA and not require client certs.

### PR DESCRIPTION
**Pull request by rphillips**
etcd can be secured with only a CA, and not require client certificates. This
fix relaxes the argument verification.

Fixes #903

### CODE REVIEW

**Comment by rphillips** [comment]
I will dig in, the lower level code needs some tweaks.

**Comment by ericchiang** [comment]
Are there no tests for these packages? Could we add one?

**Comment by diegs** [comment]
There are tests, but not for the `cmd` stuff... not sure if cobra has a good cmd testing framework?

**Comment by rphillips** [comment]
After some research, there is not a great way with cobra to do argument testing.

**Comment by ericchiang** [comment]
Was thinking something like

```
type recoverOpts struct {
    // ... fields
}

func validateRecoverOpts(o *recoverOpts) error {
    // ...
}
```

Then a test like

```
func TestValidateRecoverOpts(t *testing.T) {
    // ...
}
```

Looks like that'd be a big change though, so let's skip adding the tests.

**Comment by ericchiang** [comment]
coreosbot run e2e calico

**Comment by rphillips** [comment]
coreosbot run calico

**Comment by rphillips** [comment]
coreosbot run e2e-calico

**Comment by rphillips** [comment]
coreosbot run e2e calico

**Pull request merged**
