### PR TITLE
e2e: Add checkpointer test

### PR DESCRIPTION
**Pull request by yifan-gu**
Add checkpointer tests for bootkube.
Tests are originally from [mantle/pluton](https://github.com/coreos/mantle/blob/master/pluton/tests/bootkube/checkpointertest.go).

### CODE REVIEW

**Comment by pbx0** [comment]
Looks good so far. I'd just advocate we delete the private-key-from-file code if no one uses it. Jenkins allows use of the agent and since we can't handle encrypted private keys, I doubt any developer will use that feature either.

**Comment by yifan-gu** [comment]
rktbot run e2e

**Comment by yifan-gu** [comment]
rktbot run e2e

**Comment by yifan-gu** [comment]
Tests are passing now, but seems the checkpoint tests toke a long time (10mins / each), so the whole test times out.

**Comment by yifan-gu** [comment]
rktbot run e2e

**Comment by yifan-gu** [comment]
rktbot run e2e

**Comment by yifan-gu** [comment]
rktbot run e2e

**Comment by yifan-gu** [comment]
Looks like rebooting sometimes failed, maybe need to increase the timeout, hmm.
But doesn't seem to have to block the PR.

**Comment by pbx0** [comment]
Thats fine then, lets just file a bug for the flake with reboot and merge this. Looks like the latest failure was just bootkube failing to start which is also unrelated:

```
All self-hosted control plane components successfully started
Migrating to self-hosted etcd cluster...
I0606 20:06:23.374320    1245 migrate.go:50] created etcd cluster TPR
I0606 20:06:28.401489    1245 migrate.go:61] etcd-service IP is 10.3.0.15
I0606 20:06:28.404784    1245 migrate.go:66] created etcd cluster for migration
Error: failed to create etcd cluster
Tearing down temporary bootstrap control plane...
Error: failed to create etcd cluster
Error: failed to create etcd cluster
failed to create etcd cluster
```

**Comment by yifan-gu** [comment]
rktbot run e2e

**Comment by yifan-gu** [comment]
@pbx0 Filed an issue to track this.

**Pull request merged**
