### PR TITLE
etcd-operator: v0.4.2

### PR DESCRIPTION
**Pull request by diegs**
Should hopefully help stabilize etcd scale tests. cc @aaronlevy @abhinavdahiya @xiang90

### CODE REVIEW

**Comment by hongchaodeng** [comment]
LGTM

**Comment by diegs** [comment]
Going to try bumping hyperkube at the same time.

**Comment by diegs** [comment]
coreosbot run e2e

**Comment by diegs** [comment]
checkpointer test failed, debugging in https://github.com/kubernetes-incubator/bootkube/pull/643

**Comment by diegs** [comment]
coreosbot run e2e

**Comment by diegs** [comment]
Looks like the apiserver became destabilized after the self-etcd pod. I'm debugging locally, but kicking off a second e2e to see if it was a fluke.

**Comment by aaronlevy** [comment]
coreosbot run e2e

**Pull request merged**
