### PR TITLE
Kubernetes v1.12.3

### PR DESCRIPTION
**Pull request by aaronlevy**

### CODE REVIEW

**Comment by rphillips** [comment]
godep issue:

```01:08:37 [673482.919517] golang[6]: Difference between Gopkg.lock file and Gopkg.toml detected. Ensure all dependencies are specified in Gopkg.toml:
01:08:37 [673482.920172] golang[6]: 24a25
01:08:37 [673482.920414] golang[6]: > name="golang.org/x/oauth2"
01:08:37 [673482.920628] golang[6]: 27a29
01:08:37 [673482.920844] golang[6]: > name="google.golang.org/appengine"
01:08:37 [673482.921111] golang[6]: Makefile:34: recipe for target 'check' failed
01:08:37 [673482.921359] golang[6]: make: *** [check] Error 1
01:08:37 Build step 'Execute shell' marked build as failure```

**Comment by dghubble** [comment]
Perhaps change the vendoring separately, if the aim is to get to v1.12.3 quite soon?

**Comment by rphillips** [comment]
coreosbot run e2e calico

**Comment by rphillips** [comment]
coreosbot run e2e

**Comment by dghubble** [comment]
Anything apparent from the logs?

**Comment by rphillips** [comment]
```
logs-bootstrap-0/containers/kube-controller-manager_kube-controller-manager-855fd6d9b9-d6rrw_kube-system_a81241c5-fc9e-11e8-9d5a-0a42be2aa3d2_0.log
8:2018-12-10T17:31:33.967687979Z E1210 17:31:33.967586       1 leaderelection.go:252] error retrieving resource lock kube-system/kube-controller-manager: Get https://10.3.0.1:443/api/v1/namespaces/kube-system/endpoints/kube-controller-manager?timeout=10s: dial tcp 10.3.0.1:443: connect: connection refused
```

It appears there is an options defaulting to port 443 instead of 6443.

**Comment by dghubble** [comment]
I think that may be a red herring. The kubernetes service is port 443 and target port is 6443, so it seems right that other components access 10.3.0.1:443. I see logs like that before the kube-apiserver pod endpoint is up.

```
$ kubectl get service kubernetes
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.3.0.1     <none>        443/TCP   17h
$ kubernetes get endpoints kubernetes
NAME         ENDPOINTS            AGE
kubernetes   ACTUAL_IP:6443   17h
```

**Pull request closed without merging**
