### PR TITLE
update coredns

### PR DESCRIPTION
**Pull request by SataQiu**
update coredns image version

### CODE REVIEW

**Comment by dghubble** [comment]
You should be able to use 1.2.4

**Comment by dghubble** [comment]
I forgot to mention, the newer CoreDNS version both fixes the earlier memory leak and also requires a change in the ClusterRole. See https://github.com/poseidon/terraform-render-bootkube/commit/6a77775e52179f2ff0c71f0ad3ceea3a51822f07

**Comment by dghubble** [comment]
Leaving final approval for @rphillips

**Comment by SataQiu** [comment]
Dear @rphillips , all the tests were passed!

**Comment by aaronlevy** [comment]
Looks like the config changed a bit as well:

Upstream added `loop` and `loadbalance`:
https://github.com/coredns/deployment/blob/master/kubernetes/coredns.yaml.sed#L63-L68

Ours (for reference):
https://github.com/kubernetes-incubator/bootkube/blob/master/pkg/asset/internal/templates.go#L812-L815

I'm unfamiliar with CoreDNS, so I'm not sure the implication - but want to make sure we don't need these.

**Comment by dghubble** [comment]
From the CoreDNS plugins list, `loop` and `loadbalance` do look like useful new plugins. I haven't tried those yet. @SataQiu want to try them out?

**Comment by dghubble** [comment]
Fix s/1.2.5/1.2.4/. CoreDNS is an indpendent project and not every release is distributed via Kubernetes images. Be careful to watch upstreams and test.

**Comment by dghubble** [comment]
The new CoreDNS `loop` and `loadbalance` plugins are just "nice-to-have", they're not required. CoreDNS v1.2.4 works fine without them. 

* loop sends an initial query to detect infinite forwarding loops in configured upstream DNS servers and fast exit with an error (its a fatal misconfiguration on the network that will otherwise cause resolvers to consume memory/CPU until crashing, masking the problem)
* loadbalance randomizes the ordering of A, AAAA, and MX records in responses to provide round-robin load balancing (as usual, clients may still cache responses though)

I've started using them without issue [here](https://github.com/poseidon/terraform-render-bootkube/commit/3f3ab6b5c07f606e2c0cc6a096887962172a2680).

I'm not sure why tests fail here (I don't have access either). You could try re-running without one or both plugins or spinning it up locally to get a better idea what's going on. There must be something different about the setup here.

**Pull request merged**
