### PR TITLE
Bump k8s to 1.7.6

### PR DESCRIPTION
**Pull request by squat**
Simple bump to get Bootkube at hyperkube + k8s v1.7.6. Once this merges, I'll rebuild checkpointer and make a PR bumping that version as well.

cc @s-urbaniak @aaronlevy

### CODE REVIEW

**Comment by s-urbaniak** [comment]
@squat there seems to be something wonky with the vendoring:
```
[339243.688321] golang[5]: ../vendor/github.com/coreos/ktestutil/log-collector/scp.go:46: s.client.Glob undefined (type *sftp.Client has no field or method Glob)
[339243.688555] golang[5]: ../vendor/github.com/coreos/ktestutil/log-collector/scp.go:46: not enough arguments to return
```

**Comment by squat** [comment]
Ahh will fix now. I forgot to commit a change.

**Comment by squat** [comment]
tests look all green now.
ping @s-urbaniak @aaronlevy

**Comment by aaronlevy** [comment]
@squat looks to have some conflicts. Also - I just merged a bump in checkpointer -- doesn't look like there was a change to it in this PR (or was there another reason to need a bump?)

**Comment by squat** [comment]
@aaronlevy Looks like some conflicting things just merged. I'll have to rebase. The only thing that changed were vendored libs that the checkpointer also uses does that not necessitate a checkpointer build?

**Comment by aaronlevy** [comment]
Ah, yeah you could rebuild checkpointer in that case (likely no significant changes that would be risky, but I'll trigger tests just in case).

**Comment by aaronlevy** [comment]
coreosbot run e2e checkpointer

**Comment by dghubble** [comment]
Looks like 1.7.7 is out now

**Comment by dghubble** [comment]
Looks like an error fetching an ACI `fetch: error downloading the signature file: server asked to defer the download again`

**Comment by dghubble** [comment]
coreosbot run e2e checkpointer

**Comment by dghubble** [comment]
coreosbot run e2e checkpointer

**Comment by squat** [comment]
Closing in favor of #725

**Pull request closed without merging**
