### PR TITLE
TESTING 1.6: beta.0.updates

### PR DESCRIPTION
**Pull request by pbx0**
This is not a PR into master but into the 1.6.0-beta.0 branch which was cut from master and then had v1.6.0-beta.0+coreos.0 vendored.

This is for testing and potential pre-reviewing of 1.6 bootkube updates. The changes are mostly just about pkgs being re-shuffled around. 

cc @aaronlevy

### CODE REVIEW

**Comment by aaronlevy** [comment]
LGTM. One minor suggestion might be to use a more generic branch like: `1.6.0-updates` so we can keep iterating on this until release. Not a big deal - just gives us one integration point for all the beta testing.

**Comment by hongchaodeng** [comment]
I'm very concerned that this is changing `vendor/` directly.
Can we discuss how to resolve this dependency conflict before merging this?

**Comment by pbx0** [comment]
@hongchaodeng Yes, there is no plan to merge this, this is only to get things building for testing. 

@aaron: I'll change the base and pr branch to more generic names on the next beta update and close this PR. Alternatively, why not just base against master and include the 1.6 vendoring commits in the PR as well. Then we have a rolling set of 1.6 updates in one branch.

**Comment by pbx0** [comment]
rktbot test checkpointer please

**Comment by pbx0** [comment]
rktbot run checkpointer tests

**Comment by pbx0** [comment]
rtkbot run checkpointer tests

**Comment by pbx0** [comment]
rktbot run tests

**Comment by pbx0** [comment]
rktbot run conformance tests

**Comment by pbx0** [comment]
rktbot run checkpointer tests

**Comment by pbx0** [comment]
rktbot run conformance tests

**Comment by pbx0** [comment]
rktbot run checkpointer tests

**Comment by pbx0** [comment]
rktbot run conformance tests

**Comment by pbx0** [comment]
rktbot run conformance tests

**Comment by pbx0** [comment]
rktbot run conformance tests

**Comment by pbx0** [comment]
Closing in favor of https://github.com/kubernetes-incubator/bootkube/pull/365

**Pull request closed without merging**
