### PR TITLE
vendor: bump ktestutil for timestamp fix

### PR DESCRIPTION
**Pull request by rphillips**
bumps ktestutil to pull in the fluentd fixes for timestamps and hostnames.

### CODE REVIEW

**Comment by ericchiang** [comment]
Yay, we got timestamps

```
{"log":"Resetting endpoints for master service \"kubernetes\" to &{{ } {kubernetes  default /api/v1/namespaces/default/endpoints/kubernetes 68c66931-e051-11e7-9618-0a1cd2d6fcfc 4528 0 2017-12-13 22:03:11 +0000 UTC <nil> <nil> map[] map[] [] nil [] } [{[{10.8.0.217  <nil> <nil>}] [] [{https 443 TCP}]}]}","stream":"stderr","time":"2017-12-13T22:28:06+00:00","severity":"W","pid":"1","source":"controller.go:386","hostname":"fluentd-worker-4rqsf"}
```

Logs still aren't pretty... but this is an improvement.

**Comment by rphillips** [comment]
we can fixup the output

**Comment by rphillips** [comment]
coreosbot retest this please

**Comment by rphillips** [comment]
It was a flake. @diegs improved the flakes in a different PR, but I believe they still exist.

**Comment by ericchiang** [comment]
Okay lgtm

**Comment by rphillips** [comment]
needs a github approval

**Comment by ericchiang** [comment]
@diegs @aaronlevy can someone merge this?

**Pull request merged**
