### PR TITLE
checkpoint: use Annotations for finding checkpoint pod

### PR DESCRIPTION
**Pull request by xiang90**
/cc @aaronlevy 

Use checkpoint=name instead of just a boolean value, since we need to know its name for constructing the temp manifest anyway.

Can you please point me the place where we create the api server spec? I need to add the checkpoint annotation to it.

### CODE REVIEW

**Comment by xiang90** [comment]
Also I remove the temp in the name. I use `checkpoint` as a prefix for the checkpointed pod annotation.

**Comment by aaronlevy** [comment]
@xiang90 the api-server manifest is defined in: https://github.com/kubernetes-incubator/bootkube/blob/master/pkg/asset/internal/templates.go

I'm not sure that we do need the pod name. Doesn't seem like we're doing anything specific to the api-server. Also not sure that we need to even pre-define the checkpointPodSpec (likely can just copy the pod, then reset status / clean volumes / etc).

Pseudo code:

```
pods := getAllPods()
for _, p := range pods {
    if !p.Annotations[checkpointAnnotation] {
        continue
    }
    obj := api.Scheme.Copy(p)
    checkpointPod := obj.(v1.Pod)
    cleanVolumes(checkpointPod)
    stripNonessentialInfo(checkpointPod)
    ...
}
```

**Comment by aaronlevy** [comment]
If we do need the name, we should be able to get it from the object itself (not as an annotation). e.g. `pod.ObjectMeta.Name`

**Comment by xiang90** [comment]
@aaronlevy 

The current value in checkpoint annotation is for matching purpose. I do not want to match on name to determine if we want to checkpoint a pod.

So, I think the question is that does our checkpointer want to checkpoint ALL pods with checkpoint enabled or it should only checkpoint the pod defined here: https://github.com/kubernetes-incubator/bootkube/blob/master/cmd/checkpoint/main.go#L49.

If we want to checkpoint ALL, we need to be able to create go routines on demand and generate the checkpoint pod manifest on demand, which is a larger change.

**Comment by aaronlevy** [comment]
I think we should be able to (or try) to checkpoint any pods which have the annotation (seems easiest). If we leave it structured as-is right now, we would need to launch multiple go routines, but seems like we could just change our main loop to get all pods, then filter based on annotation, then checkpoint. But I also may be missing something.

**Comment by xiang90** [comment]
Discussed with @aaronlevy offline. We will try to make checkpointer generic, and be able to checkpoint all pods with checkpoint annotation when possible. This requires a larger change, I will try to finish it early next week.

**Comment by aaronlevy** [comment]
Closing, as this was implemented in https://github.com/kubernetes-incubator/bootkube/pull/238

**Pull request closed without merging**
