### PR TITLE
checkpointer: factor out checkpoint lib.

### PR DESCRIPTION
**Pull request by diegs**
The monolithic main.go file was becoming too unwieldy to keep working
on. This is a straightforward refactor: I moved functions into logical
files and made the main() as lightweight as possible.

### CODE REVIEW

**Comment by diegs** [comment]
coreosbot run checkpointer

**Comment by aaronlevy** [comment]
coreosbot run e2e checkpointer

**Comment by thorfour** [comment]
LGTM

**Comment by aaronlevy** [comment]
- e2e failed due to terraform destroy failing (but all tests passed).
- e2e-selfetcd w/checkpointer failed due to rkt fetch/quay:

```
image: server requested deferring the signature download
fetch: error downloading the signature file: server asked to defer the download again
```

- e2e-selfetcd failed on TestCheckpointerUnscheduleParent -- but that is using the existing checkpointer.

I'll re-run tests, as the meaningful ones (e2e, e2e w/checkpointer) both passed. I'm inclined to remove the selfhosted etcd tests soon as they're consistently flaky.

**Comment by aaronlevy** [comment]
coreosbot run e2e

**Comment by diegs** [comment]
coreosbot run e2e

**Comment by aaronlevy** [comment]
coreosbot run e2e checkpointer

**Comment by diegs** [comment]
I would be frankly surprised if any of the self-hosted etcd failures are related to my changes.

**Comment by aaronlevy** [comment]
coreosbot run e2e checkpointer

**Comment by aaronlevy** [comment]
Oh wait - that one already passed.

The self-hosted etcd tests have been disabled - feel free to merge.

**Pull request merged**
