### PR TITLE
pkg/asset: Remove self hosted etcd templates

### PR DESCRIPTION
**Pull request by klausenbusk**
It seems like this was forgotten in #828/8612599c651431248d1907b0625a4b523d0813e5

### CODE REVIEW

**Comment by klausenbusk** [comment]
Self-hosted etcd wasn't remove from the hack script either: https://github.com/kubernetes-incubator/bootkube/blob/master/hack/quickstart/init-master.sh#L10

I will fix that later.

**Comment by klausenbusk** [comment]
> I will fix that later.

Done..

**Comment by ericchiang** [comment]
ok to test

**Comment by ericchiang** [comment]
I think there are still a few more references in the `hack` directory. Feel free to remove them as part of this PR, or either @rphillips or I can do a follow up.

**Comment by rphillips** [comment]
thanks... missed these in my grepping.

**Comment by klausenbusk** [comment]
> I think there are still a few more references in the hack directory. Feel free to remove them as part of this PR, or either @rphillips or I can do a follow up.

Done, I was grepping in the wrong dir.

**Comment by ericchiang** [comment]
Can someone confirm that they've manually tested the Vagrent changes? We don't have coverage for those examples.

**Comment by rphillips** [comment]
sorry github did not refresh to see the comment... tested locally for single-node and multi-node. works

**Pull request merged**
