### PR TITLE
templates: EtcdOperator shouldn't run as nobody

### PR DESCRIPTION
**Pull request by hongchaodeng**
fix https://github.com/kubernetes-incubator/bootkube/issues/581

### CODE REVIEW

**Comment by xiang90** [comment]
lgtm.

**Comment by aaronlevy** [comment]
@hongchaodeng Does etcd operator need to run as root?

**Comment by hongchaodeng** [comment]
@aaronlevy 
Yes.
ref: https://github.com/coreos/etcd-operator/issues/806
Is it a problem? We can try prioritize if there is any issues

**Comment by aaronlevy** [comment]
Ideally nothing is running as the root user. We're trying to convert all existing objects to not require this either. What host-level privileges does etcd-operator need?

**Comment by hongchaodeng** [comment]
@aaronlevy 

No host-level priv is needed. It needs some container level priv to create some dirs, like:
```
mkdir /etc/etcd-operator: permission denied
```

**Comment by aaronlevy** [comment]
So we should probably pick a user to give to etcd-operator (nobody shouldn't own files). But giving operator root sounds unnecessary.

**Comment by hongchaodeng** [comment]
@aaronlevy 
I'm not sure but who else can create dir in `/etc` ?
And why is it a problem? It never escapes the container.

**Comment by aaronlevy** [comment]
/etc on the host or in the container fs?

**Comment by hongchaodeng** [comment]
container fs

**Comment by Quentin-M** [comment]
We also have it run as `nobody` in Tectonic: https://github.com/coreos/tectonic-installer/blob/master/modules/tectonic/resources/manifests/etcd/tectonic-etcd-operator.yaml#L32-L34. If this is actually broken and there is no way around it, please advise before code freeze.

The image/app should probably be fixed so that it can run as `nobody`. We have been doing that for all the other images (i.e. adding setcap on our ingress controller, and various chown/chmod).

**Comment by hongchaodeng** [comment]
@Quentin-M 

> We also have it run as nobody in Tectonic ...

Why do you want to set specific user? Any concern to use default user which is root?

**Comment by hongchaodeng** [comment]
Note that even if etcd operator image is set to something else, the etcd pod & backup sidecar is still running as root. There needs broader investigation on everything if there is real concern.

**Pull request closed without merging**
