### PR TITLE
Make kubecofig-in-cluster use certificate provided by apiserver

### PR DESCRIPTION
**Pull request by redbaron**
Make it tiny bit cert rotation friendlier

### CODE REVIEW

**Comment by klausenbusk** [comment]
This break local (`kubectl`) use of the kubeconfig as far as I understand.

**Comment by redbaron** [comment]
Why? This changes kubeconfig file used by kube-proxy

**Comment by klausenbusk** [comment]
> Why? This changes kubeconfig file used by kube-proxy
Sorry, my fault. :/

**Comment by ericchiang** [comment]
coreosbot test this please

lgtm

**Comment by diegs** [comment]
@redbaron can you please rebase this one?

**Comment by dghubble** [comment]
coreosbot run e2e

**Comment by dghubble** [comment]
@ericchiang you have to be firm with coreosbot, no please :P

**Comment by dghubble** [comment]
Really I think your format was also allowed, it just can't have the lgtm at the end.

**Comment by redbaron** [comment]
Ping?

**Pull request merged**
