### PR TITLE
cmd/render: Infer etcd-servers from service-cidr for self-hosted etcd

### PR DESCRIPTION
**Pull request by lblackstone**
Automatically set —etcd-servers to —service-cidr base IP + 15.
For example, if —service-cidr=10.42.0.0/24, —etcd-servers=http://10.42.0.15:2379.

Fixes https://github.com/kubernetes-incubator/bootkube/issues/329

### CODE REVIEW

**Comment by pbx0** [comment]
ok to test

**Comment by lblackstone** [comment]
This patch should fix the issue as specified in https://github.com/kubernetes-incubator/bootkube/issues/329, but the implicit override would probably be confusing to a user if they also explicitly set the `--etcd-servers` option. May want to refactor that logic a bit.

**Comment by lblackstone** [comment]
Looks like the tests failed, but I don't have permission to view the test results, so not sure if it was flakiness, or legit problems?

**Comment by pbx0** [comment]
rktbot run tests

**Comment by lblackstone** [comment]
@pbx0 RFR again.

**Pull request merged**
