### PR TITLE
e2e: remove waitForCheckpointDeactivation.

### PR DESCRIPTION
**Pull request by diegs**
Hopefully with the new, better checkpointer this shouldn't be needed
anymore.

### CODE REVIEW

**Comment by diegs** [comment]
coreosbot run e2e

**Comment by dghubble** [comment]
coreosbot run e2e

**Comment by diegs** [comment]
I guess we still need it... :-/

**Comment by dghubble** [comment]
Close?

**Comment by diegs** [comment]
I don't know. I suppose I'd like to look more closely into the failures. Adding do not merge.

**Comment by diegs** [comment]
Closing in favor of #784

**Pull request closed without merging**
