### PR TITLE
hack: Alphabetize kubelet options in hack scripts

### PR DESCRIPTION
**Pull request by lblackstone**
Alphabetize options for easier maintenance. No functional changes.

### CODE REVIEW

**Comment by pbx0** [comment]
ok to test

**Comment by pbx0** [comment]
test this please

**Comment by lblackstone** [comment]
@pbx0 Was that comment for me or the test robot?

**Comment by pbx0** [comment]
@lblackstone Sorry, that was for a test robot, we've had a number of issues with testing recently that should be resolved in a day or two.

**Comment by squat** [comment]
@lblackstone can you please rebase off of master?

**Comment by lblackstone** [comment]
@squat rebased

**Comment by lblackstone** [comment]
@pbx0 Anything blocking this PR now?

**Comment by pbx0** [comment]
ok to test

**Pull request merged**
