### PR TITLE
*: self-hosted etcd requires kube-dns to start too

### PR DESCRIPTION
**Pull request by hongchaodeng**

### CODE REVIEW

**Comment by hongchaodeng** [comment]
This is needed to make bootstrap (esp. recovery) more reliable.

@diegs @aaronlevy @xiang90

**Comment by hongchaodeng** [comment]
coreosbot run e2e

**Comment by xiang90** [comment]
lgtm

**Comment by hongchaodeng** [comment]
coreosbot run e2e

**Comment by hongchaodeng** [comment]
coreosbot run e2e

**Comment by hongchaodeng** [comment]
coreosbot run e2e

**Comment by hongchaodeng** [comment]
coreosbot run e2e

**Pull request merged**
