### PR TITLE
WIP: Bump v1.12.1

### PR DESCRIPTION
**Pull request by tomkukral**
Update Kubernetes to v1.12.1 and update CoreDNS to 1.2.2.

### CODE REVIEW

**Comment by rphillips** [comment]
Thank you for the PR. We are currently tracking an [issue](https://github.com/kubernetes-incubator/bootkube/issues/1001) with the pod checkpointer on 1.12.x. Did you see the same issue?

**Comment by tomkukral** [comment]
@rphillips We are using just bootstrap part without checkpoing so it isn't affecting us. I'll make this WIP and try to help you with #1001

**Comment by rphillips** [comment]
I pushed the mergo tweak to this PR.

**Comment by tomkukral** [comment]
Similar to #1003

**Comment by tomkukral** [comment]
Closing as duplicate of #1003

**Pull request closed without merging**
