### PR TITLE
Fix issue #96 by modifying PATH

### PR DESCRIPTION
**Pull request by luxas**
Current working directory (`.`)  is container root `/` while `/` is host root.
PATH is by default /foo,/bar => all binaries are searched for on host.
This modifies PATH to look for binaries inside the container.
Also removed some host mounts, as they are unecessary.

### CODE REVIEW

**Comment by chancez** [comment]
Not a fan. This is probably going to break disastrously due to shared libraries. Binaries in the containerFS will be using sharedlibs from the host's file system == bad.

**Comment by luxas** [comment]
But right now we aren't using executables in the container at all, right?

The problem you mentioned _already exists_. 
If the host doesn't have glibc, kubelet won't come up because it's linked to libraries on host fs

**Comment by chancez** [comment]
@luxas We are using executables in the container, nsenter, socat, mount (plus helpers), kubelet itself, etc. Everything currently uses the container's file system for tools, libraries, and binaries.

**Comment by luxas** [comment]
@chancez No, you aren't using the container fs at all right now (except for hyperkube itself)
PATH points to /, and the same for everything else.
Everything is using host (even libraries that hyperkube uses); and that may or may not be a problem (depending on how you look at it)
Play with nsenter in order to see how it works.

Repro:
```console
docker run -it --net host --pid host --privileged gcr.io/google_containers/hyperkube-amd64:v1.3.0 /bin/bash
$ ls .
bin  boot  copy-addons.sh  dev  etc  home  hyperkube  lib  lib64  make-ca-cert.sh  media  mnt  nsenter  opt  proc  root  run  sbin  setup-files.sh  srv  sys  tmp  usr  var
$ ls /
bin  boot  copy-addons.sh  dev  etc  home  hyperkube  lib  lib64  make-ca-cert.sh  media  mnt  nsenter  opt  proc  root  run  sbin  setup-files.sh  srv  sys  tmp  usr  var
$ which socat
/usr/bin/socat
$ shasum /lib/x86_64-linux-gnu/libc.so.6
c73bbf1027c5e386f19d340c72f0a7b985adcafc  /lib/x86_64-linux-gnu/libc.so.6
$ /nsenter --target=1 --mount --wd=. -- /bin/bash
$ ls .
bin  boot  copy-addons.sh  dev  etc  home  hyperkube  lib  lib64  make-ca-cert.sh  media  mnt  nsenter  opt  proc  root  run  sbin  setup-files.sh  srv  sys  tmp  usr  var
$ ls /
bin  boot  cdrom  dev  etc  etcd  home  initrd.img  initrd.img.old  lib  lib32  lib64  lost+found  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var  vmlinuz  vmlinuz.old  volumes
$ which socat
$ ldd hyperkube
	linux-vdso.so.1 =>  (0x00007ffd6eda7000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f273c088000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f273be84000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f273bab9000)
	/lib64/ld-linux-x86-64.so.2 (0x00005584919dd000)
$ shasum /lib/x86_64-linux-gnu/libc.so.6
95675a95f296148d9a98c09ffc7c1e4b21876422  /lib/x86_64-linux-gnu/libc.so.6
```

The problem here is; actually we don't need the `nsenter` hack in the beginning if we could set mount propagnation of `/var/lib/kubelet` to shared in the Kube API, but we can't https://github.com/kubernetes/kubernetes/pull/20698

**Comment by chancez** [comment]
Yeah, you're right. ideally, there is no nsenter at all, except for the `nsenter` the `kubelet` executes when calling `mount`. But we definitely _don't_ want to use anything on the host at all if possible. The main crux here is that `--containerized` will do what we want mostly, except it _will_ use the host's `mount` binary, rather than the containers. Everything else would be correctly be used from inside the container. 

When talking to @euank yesterday, we pretty much agreed mount propagation could help solve this, but we don't think that it's the completely correct approach. Instead we were thinking if we could just have some form of `--containerized` where we could ensure it uses the mount binary/shared libs from within the containerFS (instead of using the hosts like today), but doing it within the host's mount namespace via nsenter (same as `--containerized` works today).

**Pull request closed without merging**
