### PR TITLE
Allow talking to secure etcd (authentication through client certs)

### PR DESCRIPTION
**Pull request by dhawal55**
Fixes issue #244
We will need more work to support secure etcd for self-hosted etcd

### CODE REVIEW

**Comment by pbx0** [comment]
OK to test

**Comment by pbx0** [comment]
ok to test

**Comment by dhawal55** [comment]
Can anyone look at my pull requests? Really simple ones

**Comment by aaronlevy** [comment]
Hi @dhawal55, sorry for the delay.

We are planning on migrating to self-hosted etcd cluster as the default very soon (https://github.com/kubernetes-incubator/bootkube/issues/31) -- so the way each etcd node is launched (and where it sources TLS assets) will change almost completely. This is definitely something we need, but if we try to implement this functionality now, it will pretty much have to be thrown out / re-done differently very soon.

**Comment by dhawal55** [comment]
@aaronlevy The `experimental-self-hosted-etcd` currently doesn't support TLS, nor does the etcd-operator. I'm okay closing this PR if issue #31 includes TLS support for etcd.

**Comment by aaronlevy** [comment]
https://github.com/kubernetes-incubator/bootkube/issues/31 doesn't explicitly cover handling TLS support (and the initial implementation likely won't). I think we should keep https://github.com/kubernetes-incubator/bootkube/issues/244 open to track this need.

**Comment by aaronlevy** [comment]
This has been added in https://github.com/kubernetes-incubator/bootkube/pull/433

**Pull request closed without merging**
