### PR TITLE
WIP: DO NOT MERGE v1.6.0 updates

### PR DESCRIPTION
**Pull request by pbx0**
This is currently based on v1.6.0-beta.4 with flannel patched. I will update this PR as new betas are available.

### CODE REVIEW

**Comment by pbx0** [comment]
rktbot run tests

**Comment by pbx0** [comment]
rktbot run checkpointer tests

**Comment by pbx0** [comment]
rktbot run checkpointer tests

**Comment by pbx0** [comment]
rktbot run tests

**Comment by pbx0** [comment]
rktbot run conformance tests

**Comment by pbx0** [comment]
rktbot run checkpointer tests

**Comment by pbx0** [comment]
rktbot run checkpointer tests

**Comment by pbx0** [comment]
rktbot run checkpointer tests

**Comment by pbx0** [comment]
rktbot run conformance tests

**Comment by pbx0** [comment]
rktbot run tests

**Comment by pbx0** [comment]
rktbot run conformance tests

**Comment by pbx0** [comment]
rktbot run conformance tests

**Comment by pbx0** [comment]
rktbot run tests

**Comment by pbx0** [comment]
rktbot run conformance tests

**Comment by pbx0** [comment]
Seeing the scale test consistently fail:
```
./kubectl logs etcd-operator-1941361978-8g26f -n kube-system
time="2017-03-24T21:04:31Z" level=info msg="etcd-operator Version: 0.2.4"
time="2017-03-24T21:04:31Z" level=info msg="Git SHA: 7be6965"
time="2017-03-24T21:04:31Z" level=info msg="Go Version: go1.7.5"
time="2017-03-24T21:04:31Z" level=info msg="Go OS/Arch: linux/amd64"
E0324 21:04:31.843518       5 election.go:226] error retrieving resource lock kube-system/etcd-operator: Get https://10.3.0.1:443/api/v1/namespaces/kube-syste
m/endpoints/etcd-operator: dial tcp 10.3.0.1:443: getsockopt: connection refused
E0324 21:04:36.704061       5 election.go:226] error retrieving resource lock kube-system/etcd-operator: Get https://10.3.0.1:443/api/v1/namespaces/kube-syste
m/endpoints/etcd-operator: dial tcp 10.3.0.1:443: getsockopt: connection refused
E0324 21:04:42.633917       5 election.go:226] error retrieving resource lock kube-system/etcd-operator: Get https://10.3.0.1:443/api/v1/namespaces/kube-syste
m/endpoints/etcd-operator: dial tcp 10.3.0.1:443: getsockopt: connection refused
E0324 21:04:46.405816       5 election.go:226] error retrieving resource lock kube-system/etcd-operator: Get https://10.3.0.1:443/api/v1/namespaces/kube-syste
m/endpoints/etcd-operator: dial tcp 10.3.0.1:443: getsockopt: connection refused
E0324 21:04:50.776761       5 election.go:226] error retrieving resource lock kube-system/etcd-operator: Get https://10.3.0.1:443/api/v1/namespaces/kube-syste
m/endpoints/etcd-operator: dial tcp 10.3.0.1:443: getsockopt: connection refused
E0324 21:04:54.922438       5 election.go:226] error retrieving resource lock kube-system/etcd-operator: Get https://10.3.0.1:443/api/v1/namespaces/kube-syste
m/endpoints/etcd-operator: dial tcp 10.3.0.1:443: getsockopt: connection refused
E0324 21:04:59.612984       5 election.go:226] error retrieving resource lock kube-system/etcd-operator: Get https://10.3.0.1:443/api/v1/namespaces/kube-syste
m/endpoints/etcd-operator: dial tcp 10.3.0.1:443: getsockopt: connection refused
time="2017-03-24T21:05:04Z" level=info msg="finding existing clusters..." pkg=controller
time="2017-03-24T21:05:04Z" level=info msg="start running..." cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:05:04Z" level=info msg="starts running from watch version: 687" pkg=controller
time="2017-03-24T21:05:04Z" level=info msg="start watching at 687" pkg=controller
time="2017-03-24T21:05:12Z" level=info msg="Start reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:05:12Z" level=info msg="Finish reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:05:20Z" level=info msg="Start reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:05:20Z" level=info msg="Finish reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:05:28Z" level=info msg="Start reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:05:28Z" level=info msg="Finish reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:05:36Z" level=info msg="Start reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:05:36Z" level=info msg="Finish reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:05:44Z" level=info msg="Start reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:05:44Z" level=info msg="Finish reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:05:52Z" level=info msg="Start reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:05:52Z" level=info msg="Finish reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:06:00Z" level=info msg="Start reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:06:00Z" level=info msg="Finish reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:06:08Z" level=info msg="Start reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:06:08Z" level=info msg="Finish reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:06:16Z" level=info msg="Start reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:06:16Z" level=info msg="Finish reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:06:24Z" level=info msg="Start reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:06:24Z" level=info msg="Finish reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:06:32Z" level=info msg="Start reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:07:04Z" level=info msg="Finish reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:07:12Z" level=info msg="Start reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:07:12Z" level=info msg="Finish reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:07:20Z" level=info msg="Start reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:07:20Z" level=info msg="Finish reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:07:28Z" level=info msg="Start reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:07:28Z" level=info msg="Finish reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:07:36Z" level=info msg="Start reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:07:36Z" level=info msg="Finish reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:07:43Z" level=info msg="spec update: from: {1 3.1.0 false 0xc4208417c0 <nil> <nil> 0xc420346560 <nil>} to: {3 3.1.0 false 0xc420821b40 <ni
l> <nil> 0xc42032a230 <nil>}" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:07:51Z" level=info msg="Start reconciling" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:07:51Z" level=info msg="running members: kube-etcd-0000" cluster-name=kube-etcd pkg=cluster
time="2017-03-24T21:07:51Z" level=info msg="cluster membership: kube-etcd-0000" cluster-name=kube-etcd pkg=cluster
```

```
./kubectl logs kube-etcd-0001 -n kube-system
Error from server (BadRequest): container "etcd" in pod "kube-etcd-0001" is waiting to start: PodInitializing
```

```
/kubectl get pods --all-namespaces
NAMESPACE     NAME                                       READY     STATUS                  RESTARTS   AGE
kube-system   checkpoint-installer-4wgmk                 1/1       Running                 0          11m
kube-system   checkpoint-installer-qbnv5                 1/1       Running                 0          16m
kube-system   checkpoint-installer-s0p07                 1/1       Running                 0          11m
kube-system   etcd-operator-1941361978-8g26f             1/1       Running                 1          16m
kube-system   kenc-46ncd                                 1/1       Running                 0          11m
kube-system   kenc-ldl6d                                 1/1       Running                 0          16m
kube-system   kenc-pvjgf                                 1/1       Running                 0          11m
kube-system   kube-apiserver-ctkr9                       1/1       Running                 0          11m
kube-system   kube-apiserver-qz0wc                       1/1       Running                 0          11m
kube-system   kube-apiserver-t4q7l                       1/1       Running                 4          16m
kube-system   kube-controller-manager-1736101678-2lb4h   1/1       Running                 0          16m
kube-system   kube-controller-manager-1736101678-gf7qh   1/1       Running                 0          16m
kube-system   kube-dns-321336704-r9vd2                   4/4       Running                 0          16m
kube-system   kube-etcd-0000                             1/1       Running                 0          15m
kube-system   kube-etcd-0001                             0/1       Init:CrashLoopBackOff   6          10m
kube-system   kube-flannel-2m8nq                         2/2       Running                 0          11m
kube-system   kube-flannel-70gsx                         2/2       Running                 0          16m
kube-system   kube-flannel-ss4n3                         2/2       Running                 0          11m
kube-system   kube-flannel-v3mvs                         2/2       Running                 0          12m
kube-system   kube-proxy-7jgxv                           1/1       Running                 0          16m
kube-system   kube-proxy-9sbv4                           1/1       Running                 0          11m
kube-system   kube-proxy-trv15                           1/1       Running                 0          11m
kube-system   kube-proxy-wdlrl                           1/1       Running                 0          12m
kube-system   kube-scheduler-424387693-jzzk9             1/1       Running                 0          16m
kube-system   kube-scheduler-424387693-xc5c0             1/1       Running                 0          16m
kube-system   pod-checkpointer-10.240.0.17               1/1       Running                 0          10m
kube-system   pod-checkpointer-10.240.0.19               1/1       Running                 0          10m
kube-system   pod-checkpointer-10.240.0.7                1/1       Running                 0          16m
```

TPR:
```
{
  "apiVersion": "etcd.coreos.com/v1beta1",
  "kind": "Cluster",
  "metadata": {
    "name": "kube-etcd",
    "namespace": "kube-system",
    "selfLink": "/apis/etcd.coreos.com/v1beta1/namespaces/kube-system/clusters/kube-etcd",
    "uid": "1de6cb54-10d9-11e7-a384-42010af00014",
    "resourceVersion": "1129",
    "creationTimestamp": "2017-03-24T21:30:35Z"
  },
  "spec": {
    "TLS": null,
    "pod": {
      "antiAffinity": false,
      "nodeSelector": {
        "master": "true"
      },
      "resources": {}
    },
    "selfHosted": {
      "bootMemberClientEndpoint": "http://10.240.0.20:12379"
    },
    "size": 3,
    "version": "3.1.0"
  },
  "status": {
    "conditions": [
      {
        "reason": "Current cluster size: 0, desired cluster size: 1",
        "transitionTime": "2017-03-24T21:30:35.387303421Z",
        "type": "ScalingUp"
      },
      {
        "reason": "",
        "transitionTime": "2017-03-24T21:32:21.936450346Z",
        "type": "Ready"
      }
    ],
    "controlPaused": false,
    "currentVersion": "3.1.0",
    "members": {
      "ready": [
        "kube-etcd-0000"
      ]
    },
    "phase": "Running",
    "reason": "",
    "size": 1,
    "targetVersion": ""
  }
}
```

**Comment by pbx0** [comment]
rktbot run checkpointer tests

**Comment by pbx0** [comment]
rktbot run conformance tests

**Comment by pbx0** [comment]
rktbot run conformance tests

**Comment by pbx0** [comment]
Status since I will likely be gone when v1.6.0 arrives. The CI tests consistently pass except for the scale test. The CI conformance tests I was having trouble getting to run. Running pluton conformance test locally exactly as the CI runs it, it runs to success. So beyond some oddities in getting the conformance tests running, all conformance will pass. The scale seems to be the outstanding real error I was seeing.

Lastly, we should make sure not to include all commits here. The checkpointer bump was testing only, as was the hyperkube bump, and the etcd-operator shouldn't be hand edited, but rather should have a release built against v1.6.0
```
[ 4272.292097] golang[5]: SMar 24 23:37:25.661: INFO: Running AfterSuite actions on all node
[ 4272.292296] golang[5]: Mar 24 23:37:25.661: INFO: Running AfterSuite actions on node 1
[ 4272.292487] golang[5]: Ran 151 of 588 Specs in 3578.758 seconds
[ 4272.292694] golang[5]: SUCCESS! -- 151 Passed | 0 Failed | 0 Pending | 437 Skipped PASS
[ 4272.295178] golang[5]: Ginkgo ran 1 suite in 59m39.068367273s
[ 4272.295483] golang[5]: Test Suite Passed
[ 4272.296340] golang[5]: 2017/03/24 23:37:25 util.go:110: Step './hack/ginkgo-e2e.sh --ginkgo.focus=\[Conformance\]' finished in 59m39.42874936s
[ 4272.296866] golang[5]: 2017/03/24 23:37:25 e2e.go:80: Done
```

**Comment by pbx0** [comment]
rktbot run conformance tests

**Comment by yifan-gu** [comment]
rktbot run conformance tests

**Comment by yifan-gu** [comment]
Closing this as #410 is merged

**Pull request closed without merging**
