### PR TITLE
Disable garbage collector

### PR DESCRIPTION
**Pull request by lblackstone**
Fixes https://github.com/kubernetes-incubator/bootkube/issues/371

### CODE REVIEW

**Comment by lblackstone** [comment]
I disabled the GC unconditionally, but that could be revised to only happen if etcd is self-hosted if that makes more sense.

**Comment by aaronlevy** [comment]
I don't think we should disable GC unconditionally. I'm even a little hesitant to gate this to only when self-hosting etcd. I'd have to go do some research, but I'm not very sure what behavior this would trigger - and we'd be trading a known issue, but potentially other unknown issues.

Also we should consider that v1.6 should be released in a couple weeks - so we would only carry this patch for a short time.

I could be convinced on disabling the flag only when self-hosting etcd, but I think the behavior of this option needs to be well understood to make that call.

**Comment by lblackstone** [comment]
Good point about k8s 1.6 releasing soon. Seems like that should be sufficient to mitigate the reported issue.

Out of curiosity, I dug through the k8s source to see what that flag actually does. Looks like it's an alpha feature, and could probably be safely disabled. Here are some relevant links:

- https://github.com/kubernetes/kubernetes/blob/v1.5.4/pkg/registry/generic/registry/store.go#L303-L305
- https://github.com/kubernetes/kubernetes/blob/v1.5.4/pkg/registry/generic/registry/store.go#L725-L736
- https://github.com/kubernetes/kubernetes/blob/v1.5.4/pkg/apis/componentconfig/types.go#L750-L753
- https://github.com/kubernetes/kubernetes/blob/v1.5.4/cmd/kube-controller-manager/app/controllermanager.go#L573-L592

**Comment by aaronlevy** [comment]
Hmm, that would be unfortunate if an alpha feature was turned on by default. I wonder if that comment is just stale (the docs/helptext don't report as alpha - which at least has been convention in past).

If we're okay waiting - I'd probably just lean toward that (self-hosted etcd isn't stable yet for other reasons anyway).

**Comment by lblackstone** [comment]
@aaronlevy Fine by me. Would it be worth opening a new PR with just the cleanup commit?

**Comment by lblackstone** [comment]
Since this issue should be mitigated on the next release in the near future, abandoning this temporary fix.

**Pull request closed without merging**
