### PR TITLE
Enable PodSecurityPolicy by default

### PR DESCRIPTION
**Pull request by surajssd**
* Add `PodSecurityPolicy` to the admission plugins list.

* Add default permissive PSP config to be used by controller service accounts in kube-system namespace.

* Add an e2e test to test PodSecurityPolicy

* Enable coredns in kube-system namespace to run with required capabilities. So this adds a PSP config, a Role to use this PSP and a RoleBinding to bind to the coredns ServiceAccount.

Carrying forward https://github.com/kubernetes-incubator/bootkube/pull/914#issuecomment-429453475
Fixes https://github.com/kubernetes-incubator/bootkube/issues/782

### CODE REVIEW

**Comment by dghubble** [comment]
I'd need to investigate the full story and ramifications here.

Doesn't enablement impact users' namespaces (e.g. default), forcing them to have to go write a PSP? If so, I feel like they'd need much more guidance. One slight gripe is that the PSP seems to sometimes end up just mirroring what's defined in the deployment (e.g. in CoreDNS PSP, defining fsGroup and capabilities again feels tedious).

We'd probably also want to have a clear idea of what rejections looks like. Like "before this change, X could be created. After this change, creating X will result in pods stuck in Pending and `kuubectl describe` will show error Z"

**Comment by surajssd** [comment]
@dghubble are you suggesting we have a restricted PSP(with sane defaults) for all the authenticated users (`system:authenticated` group)?

**Comment by dghubble** [comment]
Oh no, quite the opposite. Asking about the scope of this. I haven't evaluated PSPs yet.

**Comment by surajssd** [comment]
For starter, atleast, can we define few sane defaults in PSP and move forward with enablement of PSP? The defaults that are not very restrictive at start, like for now allow root containers as well so we are not breaking anybody's deployment but can warn about such a changes.

WDYT?

**Comment by dghubble** [comment]
That sounds reasonable. bootkube's tests + render example can show bootkube control plane manifests can conform to the PSPs  (as you've done). And a default permissive PSP (say for anything in the default namespace) could ensure any users setting up clusters by calling `bootkube render` directly still get a working cluster (i.e. they can still deploy what they deployed before this change).

Can you include the release note you'd include with this change (similar to how upstream does)?

**Comment by bcg62** [comment]
thanks @surajssd excited to see this added. any progress on the remaining items?

**Comment by surajssd** [comment]
I have updated the PR and tests also pass now, cc: @aaronlevy @dghubble

**Pull request closed without merging**
