### PR TITLE
pkg/bootkube: fix create always printing an error

### PR DESCRIPTION
**Pull request by ericchiang**
closes https://github.com/kubernetes-incubator/bootkube/issues/932

### CODE REVIEW

**Comment by colemickens** [comment]
Has this been broken for some time then?

**Comment by ericchiang** [comment]
@colemickens yep!

**Comment by colemickens** [comment]
Okay. Did we miss it because bootkube is exitting with zero? Is that another bug? Or did we just miss it because `bootkube render` is happening remotely in our e2e and it silently keeps going?

**Comment by rphillips** [comment]
We continue running if manifest creation fails; it isn't supposed to be a hard error based on the comment here:

https://github.com/kubernetes-incubator/bootkube/blob/3fd1fd850ec3189df3445ee1913cf03426a65631/pkg/bootkube/create.go#L75-L76

**Comment by aaronlevy** [comment]
Opened https://github.com/kubernetes-incubator/bootkube/issues/937 as we should probably surface these errors at least to e2e -- could revisit the behavior of ignoring in normal case as well

**Pull request merged**
