### PR TITLE
Ensure labels are preserved

### LINKED ISSUE #378: Checkpointer should support checkpointing pod labels
They are currently stripped when sanitizing the pod spec - but these are needed for checkpointed pods to satisfy service endpoints.

### PR DESCRIPTION
**Pull request by jamiehannaford**
Fixes #378

### CODE REVIEW

**Comment by aaronlevy** [comment]
ok to test

**Comment by aaronlevy** [comment]
rktbot run checkpointer tests

**Comment by aaronlevy** [comment]
Needs manual test before merge. Make sure we're not getting extraneous messages about trying to delete mirror pods. Also should verify that this pod does not count towards the active pod count of parent objects (shouldn't based on OwnerRef - but just to sanity check).

**Comment by pbx0** [comment]
rktbot run checkpointer tests

**Comment by aaronlevy** [comment]
We should be able to merge this before 365 lands. I'll try and make some time for testing. Thank you for the contribution!

**Comment by aaronlevy** [comment]
@jamiehannaford sorry for the continually delayed review. Just got the v1.6 work out -- so would like to take another look at this. Would you mind resolving the conflicts?

**Comment by aaronlevy** [comment]
I used this PR but with some minor updates here: https://github.com/kubernetes-incubator/bootkube/issues/443

However I'm still running into ownership issues (discussed inline of that PR)

**Comment by jamiehannaford** [comment]
Cool, thanks for taking this up. I'll close this in favour of the cherry-picked one.

**Pull request closed without merging**
