### PR TITLE
pkg/asset: Update calico/cni to v1.11.2

### PR DESCRIPTION
**Pull request by dghubble**
Meant to include this with #818, we bump the calico and sidecar image together.

### CODE REVIEW

**Comment by dghubble** [comment]
coreosbot run e2e

**Comment by dghubble** [comment]
coreosbot run e2e

**Comment by dghubble** [comment]
This change doesn't affect the e2e (i.e. flannel) setup, these are the same TestCheckpointer flakes we've been seeing before.

**Comment by xiang90** [comment]
@dghubble is there an opening issue tracking the failure?

**Comment by dghubble** [comment]
coreosbot run e2e

**Comment by dghubble** [comment]
@xiang90 #816

**Comment by weikinhuang** [comment]
@dghubble any update on this?

**Pull request merged**
