### PR TITLE
e2e checkpointer test: remove node reboots

### PR DESCRIPTION
**Pull request by ericchiang**
updates https://github.com/kubernetes-incubator/bootkube/issues/851

There doesn't seem to be a good reason for this test to be rebooting nodes. Remove the reboots to see if it reduces flakey-ness.

### CODE REVIEW

**Comment by ericchiang** [comment]
coreosbot run e2e

**Comment by ericchiang** [comment]
Tests were green. Re-running again.

**Comment by colemickens** [comment]
This seems to remove any tests that show that the checkpointer can restore a cluster with downed masters though, right (since the removed code in this PR tests the presence of the checkpointed pods even before the masters are brought back up). The reboot test only ensures that rebooting everything at once leads back to a steady state. Is that sufficient?

**Comment by ericchiang** [comment]
After talking to @diegs and @abhinavdahiya, I'm not actually confident why these test reboot the nodes. Maybe @yifan-gu has some insight?

We already have tests that reboot masters and ensure the checkpointer behaves correctly when that happens. While this test is supposed to ensure that the checkpointer will clean up host files it writes if it's ever de-scheduled. The case we're testing with these reboots is unclear to me (maybe it should be a separate test?).

**Comment by ericchiang** [comment]
coreosbot run e2e

**Comment by diegs** [comment]
I'm fine to remove the reboot here. There was some dance with disabling the kubelet and starting it back up and stuff. But sometimes the kubelet takes an annoying length of time to get back into a stable state.

**Comment by ericchiang** [comment]
Damnit, this didn't work

https://jenkins-kube-lifecycle.prod.coreos.systems/job/bootkube-pr-e2e/765/console

```
19:15:50 [1095719.829133] golang[6]:     --- FAIL: TestCheckpointer/UnscheduleCheckpointer (379.22s)
19:15:50 [1095719.829358] golang[6]:     	checkpointer_test.go:77: Failed to verifyCheckpoint: should not find checkpoint "test-checkpointer" in "/etc/kubernetes/checkpoint-secrets/bootkube-e2e-3823884d-unschedulecheckpointer", error: <nil>, output: "test-checkpointer-5jcqp"
```

https://jenkins-kube-lifecycle.prod.coreos.systems/job/bootkube-pr-e2e-calico/347/console

```
[1096369.786393] golang[6]:     --- FAIL: TestCheckpointer/UnscheduleCheckpointer (379.02s)
[1096369.786945] golang[6]:     	checkpointer_test.go:77: Failed to verifyCheckpoint: should not find checkpoint "test-checkpointer" in "/etc/kubernetes/checkpoint-secrets/bootkube-e2e-58e0ac9d-unschedulecheckpointer", error: <nil>, output: "test-checkpointer-r8llj"
```

**Comment by ericchiang** [comment]
Update: this now only removes the reboot to reduce the time of the test.

**Comment by ericchiang** [comment]
coreosbot run e2e

**Comment by rphillips** [comment]
i think we could close this. thoughts?

**Comment by ericchiang** [comment]
I'd still like this to reduce the test times. No idea why e2e is failing :(

**Comment by diegs** [comment]
@ericchiang rebase? Don't think this CI merges your commit against head.

**Comment by ericchiang** [comment]
I've rebased a couple times. Will dig through the logs when I get a chance.

**Comment by ericchiang** [comment]
coreosbot run e2e calico

**Pull request merged**
