### PR TITLE
bump to 1.9

### PR DESCRIPTION
**Pull request by rphillips**

### CODE REVIEW

**Comment by rphillips** [comment]
coreosbot run e2e

**Comment by rphillips** [comment]
e2e-calico failing

```
[1036555.480308] golang[6]: === RUN   TestCheckpointer
[1036555.480839] golang[6]: === RUN   TestCheckpointer/UnscheduleCheckpointer
[1036879.362057] golang[6]: === RUN   TestCheckpointer/UnscheduleParent
[1037574.588515] golang[6]: --- FAIL: TestCheckpointer (1019.11s)
[1037574.592266] golang[6]:     --- PASS: TestCheckpointer/UnscheduleCheckpointer (323.88s)
[1037574.592557] golang[6]:     --- FAIL: TestCheckpointer/UnscheduleParent (695.23s)
[1037574.592743] golang[6]:     	checkpointer_test.go:241: verifyCheckpoint: should not find checkpoint "test-nginx" in "/etc/kubernetes/checkpoint-secrets/bootkube-e2e-53d98261-u
```

**Comment by rphillips** [comment]
looks like calico has been failing for some time

**Comment by colemickens** [comment]
Not sure if related but I spent a lot of time unsuccessfully fighting
calico and Kubernetes 1.9 with cni 0.6 last night on my personal cluster...

On Dec 19, 2017 9:30 AM, "Ryan Phillips" <notifications@github.com> wrote:

looks like calico has been failing for some time

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes-incubator/bootkube/pull/810#issuecomment-352792674>,
or mute the thread

**Comment by rphillips** [comment]
@colemickens find a solution last night?

**Comment by dghubble** [comment]
e2e-calico has been passing on commits to master so its not normal if it starts failing consistently. I was able to spin up a 1.9 cluster with Calico 2.6.3 yesterday and verified pod-to-pod connectivity, but need to test it more thoroughly.

**Comment by dghubble** [comment]
Bump to v1.9.1? This is blocking #821 and some 1.9 related kube-dns changes so it'd be good to get it finalized.

**Comment by dghubble** [comment]
In the prior run, this failed on a logs collection step, instead of the flake in TestCheckpointer/UnscheduleCheckpointer (i.e. #816).

```
[1037921.546397] golang[6]: FAIL
[1037923.337842] golang[6]: 2017/12/19 15:10:04 [56] log files collected for pods
[1037924.074727] golang[6]: 2017/12/19 15:10:05 [13] log files collected for services
[1037924.124552] golang[6]: exit status 1
[1037924.124784] golang[6]: FAIL	github.com/kubernetes-incubator/bootkube/e2e	1549.914s
```

**Comment by rphillips** [comment]
1.9.1 PR https://github.com/kubernetes-incubator/bootkube/pull/825

**Comment by rphillips** [comment]
closing in favor of #825

**Pull request closed without merging**
