### PR TITLE
pass the correct flags for calico

### PR DESCRIPTION
**Pull request by rphillips**

### CODE REVIEW

**Comment by ericchiang** [comment]
coreosbot run e2e

**Comment by aaronlevy** [comment]
fwiw e2e tests don't cover the vagrant/local hack examples

**Comment by xiang90** [comment]
> fwiw e2e tests don't cover the vagrant/local hack examples

@rphillips @aaronlevy can we create an issue for this? (or is there an existing issue already) thanks.

**Comment by aaronlevy** [comment]
opened https://github.com/kubernetes-incubator/bootkube/issues/820

**Comment by aaronlevy** [comment]
coreosbot run e2e

**Comment by rphillips** [comment]
rebased

**Comment by rphillips** [comment]
coreosbot run e2e-calico

**Pull request merged**
