### PR TITLE
checkpointer: bump to new implementation

### PR DESCRIPTION
**Pull request by aaronlevy**
Bump to new checkpointer implemented in https://github.com/kubernetes-incubator/bootkube/pull/238

### CODE REVIEW

**Comment by aaronlevy** [comment]
coreosbot test checkpoint code

**Comment by xiang90** [comment]
lgtm

**Comment by xiang90** [comment]
I am going to add the checkpoint annotation into self hosted etcd in etcd-operator.

**Comment by aaronlevy** [comment]
awesome, thanks

**Pull request merged**
