### PR TITLE
Update hyperkube image version to v1.6.6+coreos.1

### PR DESCRIPTION
**Pull request by diegs**

### CODE REVIEW

**Comment by diegs** [comment]
coreosbot run e2e

**Comment by diegs** [comment]
coreosbot run e2e

**Comment by diegs** [comment]
coreosbot run e2e

**Comment by diegs** [comment]
coreosbot run e2e

**Comment by diegs** [comment]
coreosbot run e2e

**Comment by diegs** [comment]
coreosbot run e2e

**Comment by diegs** [comment]
coreosbot run e2e

**Comment by aaronlevy** [comment]
Let's not bump this yet - the image was built with a dirty working dir (no changes to code, but need to fix nonetheless): https://github.com/coreos/tectonic-installer/pull/1128#issuecomment-309823912

**Comment by diegs** [comment]
ok, will hold off. just triggering tests to help with debugging.

**Comment by diegs** [comment]
coreosbot run e2e

**Comment by diegs** [comment]
@aaronlevy new hyperkube and tests passed, can you please lgtm again?

**Pull request merged**
