### PR TITLE
*: revert TLS bootstrapping

### PR DESCRIPTION
**Pull request by ericchiang**
Reverts various PRs related to TLS bootstrapping (in order):

* https://github.com/kubernetes-incubator/bootkube/pull/309
* https://github.com/kubernetes-incubator/bootkube/pull/316
* https://github.com/kubernetes-incubator/bootkube/pull/261

Had to manually resolve conflicts reverting #261 since #307 also modified the way we set controller flags.

Since there were a lot of changes, need to do heavy testing.

cc @pbx0 @aaronlevy @Quentin-M

### CODE REVIEW

**Comment by ericchiang** [comment]
@pbx0 I reverted the reference of `/home/core/assets/auth/bootstrap-kubeconfig` but the test is still trying to use it. Are the bring up scripts in CI distinct from the ones committed into the PR?

**Comment by pbx0** [comment]
rktbot run tests
rktbot run etcd tests

**Comment by pbx0** [comment]
rktbot run tests

**Comment by pbx0** [comment]
rktbot run tests

**Comment by pbx0** [comment]
rktbot run tests

**Comment by pbx0** [comment]
rktbot run tests

**Comment by pbx0** [comment]
rktbot run tests

**Comment by pbx0** [comment]
rktbot run etcd tests

**Comment by ericchiang** [comment]
FYI saw an error when testing the matchbox examples: https://github.com/coreos/matchbox/blob/master/Documentation/bootkube.md

Investigating

```
Feb 22 19:39:29 node1.example.com systemd[1]: Started Bootstrap a Kubernetes control plane with a temp api-server.
Feb 22 19:39:39 node1.example.com bootkube-start[1211]: pubkey: prefix: "quay.io/ericchiang/bootkube"
Feb 22 19:39:39 node1.example.com bootkube-start[1211]: key: "https://quay.io/aci-signing-key"
Feb 22 19:39:39 node1.example.com bootkube-start[1211]: gpg key fingerprint is: BFF3 13CD AA56 0B16 A898  7B8F 72AB F5F6 799D 33BC
Feb 22 19:39:39 node1.example.com bootkube-start[1211]:         Quay.io ACI Converter (ACI conversion signing key) <support@quay.io>
Feb 22 19:39:39 node1.example.com bootkube-start[1211]: Trusting "https://quay.io/aci-signing-key" for prefix "quay.io/ericchiang/bootkube" without fingerprint review.
Feb 22 19:39:39 node1.example.com bootkube-start[1211]: Added key for prefix "quay.io/ericchiang/bootkube" at "/etc/rkt/trustedkeys/prefix.d/quay.io/ericchiang/bootkube/bff313cdaa560b16a8987b8f72abf5f6799d33bc"
Feb 22 19:39:39 node1.example.com bootkube-start[1211]: image: server requested deferring the signature download
Feb 22 19:39:42 node1.example.com bootkube-start[1211]: Downloading ACI: 0 B of an unknown total size
Feb 22 19:39:42 node1.example.com bootkube-start[1211]: Downloading ACI: 4.1 KB of an unknown total size
Feb 22 19:39:43 node1.example.com bootkube-start[1211]: Downloading ACI: 217 KB of an unknown total size
Feb 22 19:39:44 node1.example.com bootkube-start[1211]: Downloading ACI: 643 KB of an unknown total size
Feb 22 19:39:45 node1.example.com bootkube-start[1211]: Downloading ACI: 1.35 MB of an unknown total size
Feb 22 19:39:46 node1.example.com bootkube-start[1211]: Downloading ACI: 2.6 MB of an unknown total size
Feb 22 19:39:47 node1.example.com bootkube-start[1211]: Downloading ACI: 4.82 MB of an unknown total size
Feb 22 19:39:48 node1.example.com bootkube-start[1211]: Downloading ACI: 7.58 MB of an unknown total size
Feb 22 19:39:49 node1.example.com bootkube-start[1211]: Downloading ACI: 11.1 MB of an unknown total size
Feb 22 19:39:50 node1.example.com bootkube-start[1211]: Downloading ACI: 14.4 MB of an unknown total size
Feb 22 19:39:51 node1.example.com bootkube-start[1211]: Downloading ACI: 18.2 MB of an unknown total size
Feb 22 19:39:52 node1.example.com bootkube-start[1211]: Downloading ACI: 22.7 MB of an unknown total size
Feb 22 19:39:53 node1.example.com bootkube-start[1211]: Downloading ACI: 26.2 MB of an unknown total size
Feb 22 19:39:54 node1.example.com bootkube-start[1211]: Downloading ACI: 28.8 MB of an unknown total size
Feb 22 19:39:54 node1.example.com bootkube-start[1211]: Downloading ACI: 29.4 MB of an unknown total size
Feb 22 19:39:55 node1.example.com bootkube-start[1211]: Downloading signature:  0 B/473 B
Feb 22 19:39:55 node1.example.com bootkube-start[1211]: Downloading signature:  473 B/473 B
Feb 22 19:39:55 node1.example.com bootkube-start[1211]: Downloading signature:  473 B/473 B
Feb 22 19:39:56 node1.example.com bootkube-start[1211]: image: signature verified:
Feb 22 19:39:56 node1.example.com bootkube-start[1211]:   Quay.io ACI Converter (ACI conversion signing key) <support@quay.io>
Feb 22 19:40:11 node1.example.com bootkube-start[1211]: [  173.285116] bootkube[5]: Running temporary bootstrap control plane...
Feb 22 19:40:11 node1.example.com bootkube-start[1211]: [  173.288326] bootkube[5]: I0222 19:40:11.363710       5 config.go:527] Will report 172.18.0.21 as public IP address.
Feb 22 19:40:11 node1.example.com bootkube-start[1211]: [  173.289539] bootkube[5]: E0222 19:40:11.364949       5 server.go:254] Failed to create clientset: parse 127.0.0.1:8080: first path segment in URL cannot contain colon
Feb 22 19:40:11 node1.example.com bootkube-start[1211]: [  173.292331] bootkube[5]: panic: parse 127.0.0.1:8080: first path segment in URL cannot contain colon
Feb 22 19:40:11 node1.example.com bootkube-start[1211]: [  173.293041] bootkube[5]: goroutine 35 [running]:
Feb 22 19:40:11 node1.example.com bootkube-start[1211]: [  173.293616] bootkube[5]: github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/core/internalversion.NewForConfigOrDie(0xc420728ea0, 0xc420738e30)
Feb 22 19:40:11 node1.example.com bootkube-start[1211]: [  173.294209] bootkube[5]:         /home/eric/src/github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/client/clientset_generated/internalclientset/typed/core/internalversion/core_client.go:132 +0x62
Feb 22 19:40:11 node1.example.com bootkube-start[1211]: [  173.294683] bootkube[5]: github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/master.(*Config).Complete(0xc420739db8, 0x0)
Feb 22 19:40:11 node1.example.com bootkube-start[1211]: [  173.295201] bootkube[5]:         /home/eric/src/github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/pkg/master/master.go:180 +0x40a
Feb 22 19:40:11 node1.example.com bootkube-start[1211]: [  173.295683] bootkube[5]: github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/cmd/kube-apiserver/app.Run(0xc42007a3c0, 0x0, 0x0)
Feb 22 19:40:11 node1.example.com bootkube-start[1211]: [  173.296779] bootkube[5]:         /home/eric/src/github.com/kubernetes-incubator/bootkube/vendor/k8s.io/kubernetes/cmd/kube-apiserver/app/server.go:347 +0x1e8d
Feb 22 19:40:11 node1.example.com bootkube-start[1211]: [  173.297381] bootkube[5]: github.com/kubernetes-incubator/bootkube/pkg/bootkube.(*bootkube).Run.func1(0xc4206b01e0, 0xc420164300)
Feb 22 19:40:11 node1.example.com bootkube-start[1211]: [  173.297916] bootkube[5]:         /home/eric/src/github.com/kubernetes-incubator/bootkube/pkg/bootkube/bootkube.go:124 +0x2f
Feb 22 19:40:11 node1.example.com bootkube-start[1211]: [  173.298399] bootkube[5]: created by github.com/kubernetes-incubator/bootkube/pkg/bootkube.(*bootkube).Run
Feb 22 19:40:11 node1.example.com bootkube-start[1211]: [  173.298850] bootkube[5]:         /home/eric/src/github.com/kubernetes-incubator/bootkube/pkg/bootkube/bootkube.go:124 +0xb0
Feb 22 19:40:11 node1.example.com systemd[1]: bootkube.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 22 19:40:11 node1.example.com systemd[1]: bootkube.service: Unit entered failed state.
Feb 22 19:40:11 node1.example.com systemd[1]: bootkube.service: Failed with result 'exit-code'.
```

**Comment by Quentin-M** [comment]
@ericchiang Missing protocol segment.

**Comment by ericchiang** [comment]
Yep, was a Go 1.8 change.[0] Got this working using matchbox.

Will open an issue upstream for the internalclientset error.

[0] https://beta.golang.org/doc/go1.8#net_url

**Pull request merged**
