### PR TITLE
quickstart: fix for ca.crt

### PR DESCRIPTION
**Pull request by aaronlevy**

### CODE REVIEW

**Comment by aaronlevy** [comment]
rktbot run tests

**Comment by pbx0** [comment]
Is there anyway to delete the `extract_master_endpoint` function entirely here and copy over the cert generated in the assets?

**Comment by aaronlevy** [comment]
We still need the kubeconfig - so we could remove most of that function and just extract the ca.crt

**Comment by aaronlevy** [comment]
But this is a fix because HEAD is currently broken - could do that in a separate PR (and I saw you had that in your hack+self-hosted etcd pr too)

**Comment by aaronlevy** [comment]
@pbx0 it's newly necessary to keep the extracted CA because we're using it to turn on AuthN to the kubelet api

**Comment by ericchiang** [comment]
FYI these changes worked using the AWS quickstart manually.

**Pull request merged**
