### PR TITLE
vendor: etcd-operator

### PR DESCRIPTION
**Pull request by hongchaodeng**
This is to vendor etcd-operator spec only.

### CODE REVIEW

**Comment by hongchaodeng** [comment]
@aaronlevy @xiang90 
Let's get this merge first.

**Comment by xiang90** [comment]
Can we just vendor the spec part? not the entire operator?

**Comment by hongchaodeng** [comment]
Updated to vendor spec only.

**Comment by xiang90** [comment]
LGTM

**Comment by aaronlevy** [comment]
lgtm - but holding off on merging until I can get a version bump release out (will be today)

**Comment by hongchaodeng** [comment]
Discussed with @aaronlevy and we are going to combine this PR with https://github.com/kubernetes-incubator/bootkube/issues/259

**Pull request closed without merging**
