### PR TITLE
templates: increase API server verbosity

### PR DESCRIPTION
**Pull request by ericchiang**
This PR is intended to help debug our e2e test flakes https://github.com/kubernetes-incubator/bootkube/issues/824. It's not intended to be merged.

### CODE REVIEW

**Comment by xiang90** [comment]
maybe our e2e test should always start the API server with v6?

**Comment by ericchiang** [comment]
@xiang90 yeah but I don't think the audit changes are appropriate for everyone. Would require a knob.

**Comment by xiang90** [comment]
> @xiang90 yeah but I don't think the audit changes are appropriate for everyone.

agree

> Would require a knob.

i hate to add the knob just for testing in general. we probably can figure out something better. one ugly approach is to add it in testing scripts after running bootkube render.

**Comment by ericchiang** [comment]
Found https://github.com/kubernetes-incubator/bootkube/issues/837

Closing for now.

**Pull request closed without merging**
