### PR TITLE
Added service-cluster-ip-range as flag to bootkube start

### LINKED ISSUE #236: Add flag to pass cluster CIDR to bootkube render
When I run bootkube to render assets, it assumes service-cluster-ip-range to be 10.3.0.0/24 and allocates etcd clusterIP and kube-dns clusterIP from that range. Make this as a parameter that can be passed to `bootkube render`.

Why does kube-proxy daemonset need to pass `--cluster-cidr` to `hyperkube proxy` image? Documentation says "It is used to bridge traffic coming from outside of the cluster". How does it work when using flanneld (its value is same as that set in etcd for /coreos.com/network/config Network value) and can this be made a parameter too so if not passed, it will not be set?

### PR DESCRIPTION
**Pull request by dhawal55**
Fixes #236

### CODE REVIEW

**Comment by aaronlevy** [comment]
Changing of the service IP ends up touching many different components. And while it really does need to be a configurable -- I'm hesitant to try and plumb this through as a configuration option right now.

As an example (and I'm likely forgetting things) - For this change to work properly, it also requires changes to the on-host kubelet, self-hosted kubelet, self-hosted controller-manager,  dns service manifest, validation of podCidrs, and templating tls asset generation.

It ends up being a fairly intrusive change. And while I'm not outright opposed to making this a configurable, it does open a pretty big door for complexity. Any change which would require coordination of flags between `bootkube render` and `bootkube start` means that we can leave users in a place where generated assets no longer work unless you use the correct flags (which I really want to avoid).

Longer term, I believe minimizing this risk will come in a couple stages:

* Changing `bootkube start` to using static manifests for the temporary control-plane, rather than compiled-in components (https://github.com/kubernetes-incubator/bootkube/issues/168). This will mean that `bootkube render` will create all the information needed for the temporary control-plane, and `bootkube start` can source all of that information from static manifests (not runtime flags).

* Changing `bootkube render` to source from versioned configuration, rather than runtime flags. See some of the brainstorming discussion here: https://github.com/kubernetes-incubator/bootkube/issues/106

**Comment by dhawal55** [comment]
@aaronlevy I like the idea of `bootkube start` using static manifests for temporary control-plane. Currently, I'm not using `bootkube render` to generate assets becuase there are lots of configuration missing. I generate my own assets dir and pass it to `bootkube start`. It makes sense to do the same for temporary control-plane too. Will the init_master.sh script be responsible for copying over the static manifests to `/etc/kubernetes/manifests` directory?

**Comment by aaronlevy** [comment]
@dhawal55 init-master.sh just copies from the remote location to your local box (so that you have a copy of things like the CA cert, etc.). But it merely executes bootkube remotely.

I think in the new mode of operation we would still do the same (execute bootkube remotely) -- but with `bootkube start --cluster-dir=foo`, the cluster-dir would also contain manifests for the "temporary" control plane. 

This would allow you to similarly not use `render` (or use, then modify) -- and self provide those assets however you see fit (and just reference a `--cluster-dir`)

**Comment by aaronlevy** [comment]
I'm going to close this PR in favor of a (yet to be implemented) alternative solution discussed in: https://github.com/kubernetes-incubator/bootkube/issues/236#issuecomment-279797787

**Pull request closed without merging**
