### PR TITLE
*: bootFromBackupEtcd should use `dnsPolicy: ClusterFirstWithHostNet`

### PR DESCRIPTION
**Pull request by hongchaodeng**
Current master is broken on self-hosted etcd recovery. We need this to fix it.
@diegs @aaronlevy @xiang90

### CODE REVIEW

**Comment by hongchaodeng** [comment]
Current master is broken on recovery. We need this to fix it.
@diegs @aaronlevy @xiang90

**Comment by hongchaodeng** [comment]
cc @Quentin-M @squat

**Comment by xiang90** [comment]
lgtm.

**Comment by xiang90** [comment]
coreosbot run e2e

**Comment by hongchaodeng** [comment]
coreosbot run e2e

**Comment by hongchaodeng** [comment]
coreosbot run e2e

**Pull request merged**
