### PR TITLE
Minor docs fix to re-run master tests

### PR DESCRIPTION
**Pull request by dghubble**
Mainly intended to validate that master is in a decent state since there are some failing PRs.

### CODE REVIEW

**Comment by dghubble** [comment]
coreosbot run e2e

**Comment by dghubble** [comment]
Sadness. So I suppose this shows the flannel failure _is_ unique to #1033, but the calico failure may be present on master (which could account for #1025 and #1032).

Unless this test is just flaky, only #1027 and #1030 are recent. I'll try reverting mine.

**Comment by rphillips** [comment]
coreosbot run e2e

**Comment by rphillips** [comment]
There was a syscall error... just rebooted the workers.

coreosbot run e2e

**Comment by rphillips** [comment]
coreosbot run e2e

**Comment by rphillips** [comment]
coreosbot run e2e calico

**Comment by rphillips** [comment]
potential fix: https://github.com/kubernetes-incubator/bootkube/pull/1035

**Pull request closed without merging**
