### PR TITLE
apiserver: run as non-root user.

### PR DESCRIPTION
**Pull request by diegs**
Changes the apiserver defaults to listen on port 6443 and use a non-root
user. The port matches the upstream default and reflects best practices.

Production users can put the apiserver behind a load-balancer to forward
443 to 6443.

### CODE REVIEW

**Comment by rphillips** [comment]
though the build is failing

**Comment by dghubble** [comment]
You might have a read through https://github.com/poseidon/terraform-render-bootkube/pull/17 where there was some discussion about the repercussions of this change. I'm not opposed to moving toward it, but it necessitates a v0.10.0 imo.

**Comment by diegs** [comment]
@dghubble yes, v0.10.0 would be prudent, though this is basically just changing the default of an option that has always existed (and updating all the examples to use the new default).

PR tests are very flaky. I'm close to making them better in #784

**Comment by redbaron** [comment]
Do we need to change port at all? Running as non root and  adding `CAP_NET_BIND_SERVICE` capability in security context should be enough

**Comment by diegs** [comment]
I did some research on using `CAP_NET_BIND_SERVICE` in the past. Due to Docker limitations granting it to the user does not work. It must be added to the binary, which would require a modification to the hyperkube image, which upstream will not accept. They recommend using port 6443 which is actually a reasonable stance in my opinion.

**Comment by redbaron** [comment]
Googled,  found your comments :) Can't initcontainer help here? Set capability on hyperkube binary at start time. Hmm, probably  just binding to a non privileged port is easier.

**Comment by diegs** [comment]
coreosbot run e2e checkpointer

**Comment by diegs** [comment]
coreosbot run e2e checkpointer

**Comment by xiang90** [comment]
@diegs 

are all the tests failure tracked? it is useful to link the failure issues in the rerun comment so we know all flakes are tracked. thanks!

**Comment by diegs** [comment]
Flake is #816. Was just doing some testing to see if #814 solves this use case (it does!)

**Comment by diegs** [comment]
coreosbot run e2e

**Pull request merged**
